namespace Solnet.Metaplex.Candymachine.Errors
{
#pragma warning disable CS1591
    public enum CandyMachineErrorKind : uint
        {
            IncorrectOwner = 6000U,
            Uninitialized = 6001U,
            MintMismatch = 6002U,
            IndexGreaterThanLength = 6003U,
            NumericalOverflowError = 6004U,
            TooManyCreators = 6005U,
            UuidMustBeExactly6Length = 6006U,
            NotEnoughTokens = 6007U,
            NotEnoughSOL = 6008U,
            TokenTransferFailed = 6009U,
            CandyMachineEmpty = 6010U,
            CandyMachineNotLive = 6011U,
            HiddenSettingsConfigsDoNotHaveConfigLines = 6012U,
            CannotChangeNumberOfLines = 6013U,
            DerivedKeyInvalid = 6014U,
            PublicKeyMismatch = 6015U,
            NoWhitelistToken = 6016U,
            TokenBurnFailed = 6017U,
            GatewayAppMissing = 6018U,
            GatewayTokenMissing = 6019U,
            GatewayTokenExpireTimeInvalid = 6020U,
            NetworkExpireFeatureMissing = 6021U,
            CannotFindUsableConfigLine = 6022U,
            InvalidString = 6023U,
            SuspiciousTransaction = 6024U,
            CannotSwitchToHiddenSettings = 6025U,
            IncorrectSlotHashesPubkey = 6026U,
            IncorrectCollectionAuthority = 6027U,
            MismatchedCollectionPDA = 6028U,
            MismatchedCollectionMint = 6029U,
            SlotHashesEmpty = 6030U,
            MetadataAccountMustBeEmpty = 6031U,
            MissingSetCollectionDuringMint = 6032U,
            NoChangingCollectionDuringMint = 6033U,
            CandyCollectionRequiresRetainAuthority = 6034U,
            GatewayProgramError = 6035U,
            NoChangingFreezeDuringMint = 6036U,
            NoChangingAuthorityWithCollection = 6037U,
            NoChangingTokenWithFreeze = 6038U,
            InvalidThawNft = 6039U,
            IncorrectRemainingAccountsLen = 6040U,
            MissingFreezeAta = 6041U,
            IncorrectFreezeAta = 6042U,
            FreezePDAMismatch = 6043U,
            EnteredFreezeIsMoreThanMaxFreeze = 6044U,
            NoWithdrawWithFreeze = 6045U,
            NoWithdrawWithFrozenFunds = 6046U,
            MissingRemoveFreezeTokenAccounts = 6047U,
            InvalidFreezeWithdrawTokenAddress = 6048U,
            NoUnlockWithNFTsStillFrozen = 6049U,
            SizedCollectionMetadataMustBeMutable = 6050U,
            CannotSwitchFromHiddenSettings = 6051U
        }
    }
